using BackendUiEval.Grpc;
using Google.Protobuf.WellKnownTypes;

namespace BackendUiEval.Services;

public class TodoTickerService : BackgroundService
{
    private static readonly TimeSpan Interval = TimeSpan.FromSeconds(10);
    private const int BatchSize = 5;

    private static readonly string[] Descriptions =
    {
        "Auto: stand-up reminder", "Auto: grocery top-up", "Auto: take a break",
        "Auto: check inbox", "Auto: stretch session",
    };

    private readonly TodoStore _store;
    private readonly ILogger<TodoTickerService> _log;
    private readonly Random _rng = new();

    public TodoTickerService(TodoStore store, ILogger<TodoTickerService> log)
    {
        _store = store;
        _log = log;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _log.LogInformation("TodoTickerService started: +{Batch} todos every {Seconds}s", BatchSize, Interval.TotalSeconds);
        using var timer = new PeriodicTimer(Interval);
        try
        {
            while (await timer.WaitForNextTickAsync(stoppingToken))
            {
                for (var i = 0; i < BatchSize; i++)
                    _store.Add(BuildSample());
            }
        }
        catch (OperationCanceledException)
        {
            // host shutting down
        }
    }

    private Todo BuildSample() => new()
    {
        Description = Descriptions[_rng.Next(Descriptions.Length)],
        Detail = "Auto-generated by the ticker.",
        Type = (Grpc.TodoType)(_rng.Next(3) + 1),
        Person = (Grpc.Person)(_rng.Next(2) + 1),
        State = Grpc.TodoState.Ready,
        Date = Timestamp.FromDateTime(DateTime.UtcNow),
    };
}
